# Generated by Django 2.2.6 on 2020-04-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('coordinates', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TouristClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('class_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_position', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourist_app.MapObject')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourist_app.IndividualRoute')),
            ],
        ),
        migrations.AddField(
            model_name='mapobject',
            name='object_type',
            field=models.ManyToManyField(to='Tourist_app.ObjType'),
        ),
        migrations.AddField(
            model_name='individualroute',
            name='obj_map',
            field=models.ManyToManyField(through='Tourist_app.RouteComposition', to='Tourist_app.MapObject'),
        ),
        migrations.AddField(
            model_name='individualroute',
            name='route_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorRouteComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_position', models.IntegerField()),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_map_obj', to='Tourist_app.MapObject')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_id', to='Tourist_app.AuthorRoute')),
            ],
        ),
        migrations.AddField(
            model_name='authorroute',
            name='map_object',
            field=models.ManyToManyField(through='Tourist_app.AuthorRouteComposition', to='Tourist_app.MapObject'),
        ),
        migrations.AddField(
            model_name='authorroute',
            name='route_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.ManyToManyField(to='Tourist_app.TouristClass'),
        ),
    ]
