# Generated by Django 2.2.6 on 2020-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_app', '0004_auto_20200411_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='tourist', max_length=15, verbose_name='Роль'),
        ),
    ]
