# Generated by Django 2.2.6 on 2020-03-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='kit.StudentGroup'),
        ),
    ]
