# Generated by Django 2.2.6 on 2020-04-01 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_auto_20200320_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualroutestep',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kit.IndividualRouteStep'),
        ),
    ]
